version: '3.3'

services:
  db:
    image: postgres:16-alpine
    container_name: vakansai_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vacancies
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: vakansai_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
    restart: always

volumes:
  postgres_data:

