# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file
# (optional)
# timezone =

# max length of characters to prepend to the
# filename of a new migration script
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc files to be created
# (optional)
# sourceless = false

# search path for migration scripts
# (optional, defaults to script_location)
# version_locations = %(here)s/bar:%(here)s/bat:migrations

# version path separator; defaults to None
# (optional)
# version_path_separator = :

# set to 'true' to use the 'flat' layout
# (optional)
# output_encoding = utf-8

sqlalchemy.url = postgresql+asyncpg://user:password@localhost/vacancies

[post_write_hooks]
# post_write_hooks allows scripts to run after generating a migration
# file.

# format using "black"
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REW_FILE

[logging]
# default logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S
